apiVersion: v1
kind: Service
metadata:
  name: lorgnon-api-service
spec:
  type: NodePort
  selector:
    app: lorgnon-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30007  # accès via localhost:30007

